create table member
(
    id       bigint generated by default as identity,
    email    varchar(255),
    password varchar(255),
    city     varchar(255),
    street   varchar(255),
    zipcode  varchar(255),
    primary key (id)
);

